{% set version = "2.7.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-climate4r
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/SantanderMetGroup/climate4r-meta/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 294bd0b12616e0179204e963a3eb5a63a7a87f80b8746d6f92f560cba9b210ff

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

requirements:
  host:
    - r-base
    - r-loader.java        ==1.2.1
    - r-transformer        ==2.2.2
    - r-climate4r.udg      ==0.2.6
    - r-loader.2nc         ==0.1.3
    - r-convertr           ==0.2.1
    - r-downscaler         ==3.3.4
    - r-loader             ==1.8.4
    - r-loader.ecoms       ==1.4.8
    - r-downscaler.keras   ==1.1.1
    - r-visualizer         ==1.6.4
    - r-geoprocessor       ==0.2.2
    - r-climate4r.climdex  ==0.2.3
    - r-climate4r.indices  ==0.3.1
    - r-firedanger         ==1.1.0
    - r-value              ==2.2.4
    - r-climate4r.value    ==1.0.2
    - r-mopa               ==1.1.2
    - r-drought4r          ==0.3.1
    - r-climate4r.datasets ==0.0.1
    - r-c4r-calibrator     ==0.2.0
    - r-climate4r.hub      ==0.0.1
  run: 
    - r-base
    - r-loader.java        ==1.2.1
    - r-transformer        ==2.2.2
    - r-climate4r.udg      ==0.2.6
    - r-loader.2nc         ==0.1.3
    - r-convertr           ==0.2.1
    - r-downscaler         ==3.3.4
    - r-loader             ==1.8.4
    - r-loader.ecoms       ==1.4.8
    - r-downscaler.keras   ==1.1.1
    - r-visualizer         ==1.6.4
    - r-geoprocessor       ==0.2.2
    - r-climate4r.climdex  ==0.2.3
    - r-climate4r.indices  ==0.3.1
    - r-firedanger         ==1.1.0
    - r-value              ==2.2.4
    - r-climate4r.value    ==1.0.2
    - r-mopa               ==1.1.2
    - r-drought4r          ==0.3.1
    - r-climate4r.datasets ==0.0.1
    - r-c4r-calibrator     ==0.2.0
    - r-climate4r.hub      ==0.0.1

test:
  commands:
    - $R -e "library('climate4R')"           # [not win]
    - "\"%R%\" -e \"library('climate4R')\""  # [win]

about:
  home: https://github.com/SantanderMetGroup/climate4R
  summary: R Framework for Climate Data Access and Post-processing.
  dev_url: https://github.com/SantanderMetGroup/climate4R-meta
  doc_url: https://github.com/SantanderMetGroup/climate4R
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
extra:
  recipe-maintainers:
    - conda-forge/r
    - cofinoa
    - mor427unican
